// ==========================================
// GLOBAL VARIABLES & DOM ELEMENTS
// ==========================================
let allSubjects = [];
let currentAssignments = [];
let currentSubjectInfo = null;
let currentView = 'subjects';

const subjectContainer = document.getElementById("subjectContainer");
const assignmentContainer = document.getElementById("assignmentContainer");
const searchInput = document.getElementById("searchInput");
const backBtn = document.getElementById("backBtn");
const downloadOptions = document.getElementById("downloadOptions");
const pageTitle = document.getElementById("pageTitle");
const pageDesc = document.getElementById("pageDesc");
const noResults = document.getElementById("noResults");

// ==========================================
// INITIAL LOAD
// ==========================================
fetch("subjects.json")
  .then(res => res.json())
  .then(data => {
    allSubjects = data;
    renderSubjects(data);
  })
  .catch(err => console.error("Error loading subjects:", err));

// ==========================================
// RENDER FUNCTIONS
// ==========================================
function renderSubjects(data) {
  currentView = 'subjects';
  subjectContainer.classList.remove("hidden");
  assignmentContainer.classList.add("hidden");
  backBtn.classList.add("hidden");
  downloadOptions.classList.add("hidden"); 
  
  pageTitle.innerText = "🎓 College Lab Repository";
  pageDesc.innerText = "Select a subject to view assignments";
  searchInput.placeholder = "Search subjects...";
  searchInput.value = ""; 
  subjectContainer.innerHTML = "";

  if (data.length === 0) {
    noResults.classList.remove("hidden");
    return;
  }
  noResults.classList.add("hidden");

  data.forEach(subject => {
    const card = document.createElement("div");
    card.className = "card subject-card";
    card.innerHTML = `
      <div class="subject-icon">${subject.icon}</div>
      <h2>${subject.subjectName}</h2>
      <p class="subject-desc">${subject.description}</p>
      <button onclick="openSubject('${subject.id}')">View Assignments →</button>
    `;
    subjectContainer.appendChild(card);
  });
}

function openSubject(id) {
  const subject = allSubjects.find(s => s.id === id);
  if (!subject) return;

  currentSubjectInfo = subject;
  pageTitle.innerText = `${subject.icon} ${subject.subjectName}`;
  pageDesc.innerText = "Browse assignments and solutions below";
  searchInput.placeholder = "Search assignments...";
  searchInput.value = "";
  
  subjectContainer.classList.add("hidden");
  assignmentContainer.classList.remove("hidden");
  backBtn.classList.remove("hidden");
  downloadOptions.classList.remove("hidden");
  currentView = 'assignments';

  fetch(subject.file)
    .then(res => res.json())
    .then(data => {
      currentAssignments = data;
      renderAssignments(currentAssignments);
    })
    .catch(err => {
      console.error("Error loading assignments:", err);
      assignmentContainer.innerHTML = "<p class='error'>Failed to load assignments.</p>";
    });
}

function renderAssignments(assignments) {
  assignmentContainer.innerHTML = "";
  if (assignments.length === 0) {
    noResults.classList.remove("hidden");
    return;
  }
  noResults.classList.add("hidden");

  assignments.forEach((a) => {
    const card = document.createElement("div");
    card.className = "card";
    card.innerHTML = `
      <div>
        <span class="card-badge">${a.assignment}</span>
        <h2>${a.title}</h2>
      </div>
      <button onclick="openModalByTitle('${a.title.replace(/'/g, "\\'")}')">View Solution →</button>
    `;
    assignmentContainer.appendChild(card);
  });
}

function goBack() {
  currentSubjectInfo = null;
  currentAssignments = [];
  renderSubjects(allSubjects);
}

// ==========================================
// DOWNLOAD FUNCTIONS (FIXED)
// ==========================================

function downloadTXT() {
  if (!currentAssignments.length) return alert("No content to save!");

  let content = `SUBJECT: ${currentSubjectInfo.subjectName.toUpperCase()}\n`;
  content += `Lab Manual - Generated by College Lab Repository\n`;
  content += `=================================================\n\n`;

  currentAssignments.forEach(exp => {
    content += `Experiment: ${exp.assignment}\nTitle: ${exp.title}\n`;
    content += `-------------------------------------------------\n`;
    exp.questions.forEach(q => {
      content += `>> ${q.question}\n`;
      content += `${cleanTextForFile(q.answer)}\n\n`;
    });
    content += `=================================================\n\n`;
  });

  const blob = new Blob([content], { type: 'text/plain' });
  saveFile(blob, `${currentSubjectInfo.id}_manual.txt`);
}

// 🔥 FIXED PDF GENERATION FUNCTION 🔥
function downloadPDF() {
  if (!currentAssignments.length) return alert("No content to save!");

  const element = document.createElement('div');
  element.style.padding = '20px';
  element.style.fontFamily = 'Arial, sans-serif';
  element.innerHTML = `
    <h1 style="text-align:center; color:#1d4ed8;">${currentSubjectInfo.subjectName}</h1>
    <p style="text-align:center; color:#64748b;">Lab Manual & Solutions</p>
    <hr style="margin: 20px 0;">
  `;

  currentAssignments.forEach(exp => {
    let expHTML = `
      <div style="margin-bottom: 30px; page-break-inside: avoid;">
        <h3 style="background:#f1f5f9; padding:10px; border-left: 5px solid #3b82f6;">
          ${exp.assignment}: ${exp.title}
        </h3>
    `;
    
    exp.questions.forEach(q => {
      // 1. Temporary element to parse HTML
      let tempDiv = document.createElement('div');
      tempDiv.innerHTML = q.answer;

      // 2. Escape Code Blocks safely
      const pres = tempDiv.querySelectorAll('pre');
      pres.forEach(pre => {
        // Get raw text (preserving tags like <html>)
        let rawCode = pre.innerText || pre.textContent;
        
        // Escape HTML characters manually
        let escapedCode = rawCode
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;");
            
        // Set styled escaped content
        pre.innerHTML = escapedCode;
        pre.style.cssText = "background:#1e293b; color:#fff; padding:15px; border-radius:5px; white-space:pre-wrap; font-size:12px; overflow-x:hidden; font-family: monospace;";
      });

      // 3. Add sanitized content to PDF
      expHTML += `
        <div style="margin-top:15px;">
          <h4 style="margin-bottom:5px; color:#334155; border-bottom:1px solid #eee; display:inline-block;">${q.question}</h4>
          <div style="font-size:14px; line-height:1.6;">${tempDiv.innerHTML}</div>
        </div>
      `;
    });

    expHTML += `</div><hr style="border:0; border-top:1px dashed #ccc; margin:20px 0;">`;
    element.innerHTML += expHTML;
  });

  const opt = {
    margin: [10, 10],
    filename: `${currentSubjectInfo.id}_Lab_Manual.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  };

  html2pdf().set(opt).from(element).save();
}

function saveFile(blob, filename) {
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.URL.revokeObjectURL(url);
}

// 🔥 CLEANER FUNCTION FOR TEXT FILES 🔥
function cleanTextForFile(html) {
  let codeBlocks = [];
  let protectedHtml = html.replace(/<pre>([\s\S]*?)<\/pre>/gi, function(match, code) {
    codeBlocks.push(code);
    return `___CODE_BLOCK_${codeBlocks.length - 1}___`;
  });

  let text = protectedHtml.replace(/<br\s*\/?>/gi, '\n');
  text = text.replace(/<\/li>/gi, '\n');
  text = text.replace(/<li>/gi, ' - ');

  let tempDiv = document.createElement("div");
  tempDiv.innerHTML = text;
  let cleanText = tempDiv.innerText || tempDiv.textContent || "";

  codeBlocks.forEach((code, index) => {
    cleanText = cleanText.replace(`___CODE_BLOCK_${index}___`, `\n--- CODE START ---\n${code}\n--- CODE END ---\n`);
  });

  return cleanText;
}

// ==========================================
// SEARCH & UTILITIES
// ==========================================
searchInput.addEventListener("input", function () {
  const key = this.value.toLowerCase();
  if (currentView === 'subjects') {
    const filteredSubjects = allSubjects.filter(s => 
      s.subjectName.toLowerCase().includes(key) || 
      s.description.toLowerCase().includes(key)
    );
    subjectContainer.innerHTML = "";
    if (filteredSubjects.length === 0) {
      noResults.classList.remove("hidden");
    } else {
      noResults.classList.add("hidden");
      filteredSubjects.forEach(subject => {
        const card = document.createElement("div");
        card.className = "card subject-card";
        card.innerHTML = `
          <div class="subject-icon">${subject.icon}</div>
          <h2>${subject.subjectName}</h2>
          <p class="subject-desc">${subject.description}</p>
          <button onclick="openSubject('${subject.id}')">View Assignments →</button>
        `;
        subjectContainer.appendChild(card);
      });
    }
  } else {
    const filteredAssignments = currentAssignments.filter(a =>
      a.title.toLowerCase().includes(key) ||
      a.assignment.toLowerCase().includes(key) ||
      a.questions.some(q => q.question.toLowerCase().includes(key))
    );
    renderAssignments(filteredAssignments);
  }
});

function openModalByTitle(title) {
  const modal = document.getElementById("modal");
  const modalTitle = document.getElementById("modalTitle");
  const body = document.getElementById("modalBody");
  
  const a = currentAssignments.find(item => item.title === title);
  if (!a) return;

  modalTitle.innerText = `${a.assignment}: ${a.title}`;
  body.innerHTML = "";

  a.questions.forEach(q => {
    let content = q.answer;
    const div = document.createElement("div");
    div.className = "question";
    div.innerHTML = `<h3>${q.question}</h3><div class="answer-content">${content}</div>`;
    
    const pres = div.querySelectorAll("pre");
    pres.forEach(pre => {
      const wrapper = document.createElement("div");
      wrapper.className = "code-wrap";
      wrapper.innerHTML = `
        <div class="code-header">
          <div class="window-dots"><span class="dot red"></span><span class="dot yellow"></span><span class="dot green"></span></div>
          <button class="copy-btn">Copy</button>
        </div>
      `;
      pre.parentNode.insertBefore(wrapper, pre);
      wrapper.appendChild(pre);
      
      wrapper.querySelector(".copy-btn").addEventListener("click", () => {
        copyToClipboard(pre.innerText);
      });
    });
    body.appendChild(div);
  });

  modal.classList.remove("hidden");
  setTimeout(() => modal.classList.add("active"), 10);
}

function closeModal() {
  const modal = document.getElementById("modal");
  modal.classList.remove("active");
  setTimeout(() => modal.classList.add("hidden"), 300);
}

function copyToClipboard(text) {
  navigator.clipboard.writeText(text).then(() => {
    const toast = document.getElementById("toast");
    toast.classList.remove("hidden");
    setTimeout(() => { toast.classList.add("hidden"); }, 2000);
  });
}